### ISSUE TITLE
consider `create-capi-app`

### ISSUE THREAD

**Issue by vjjft** [paritytech/docs.capi.dev#30]
*see also:*
- #36

**Comment by harrysolovay** [comment]
We have a WIP `init` command. We could add any other scaffolding to this script. Currently, one can `npx init capi`, although it's brittle. Should we rename this issue `revisit CLI's init command`?

**Comment by vjjft** [comment]
@harrysolovay imo they are different and sufficiently distinct to warrant separate threads, so I created #36 

I will follow up with some details of why I think they are different

**Comment by vjjft** [comment]
I had some offline discussion with @tjjfvi and better understand the existing `capi init` feature.  Thus, I think this should be supplanted by:
- #38 
- #36
